version: '3'
services:

  backend:
    image: hackathon-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: hackathon-backend
    ports:
      - 8080:8080
  
  frontend:
    image: hackathon-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackathon-frontend
    ports:
      - 3000:3000

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: hackathon2023-db
    ports:
      - "3306:3306"