version: '3'
services:

  backend:
    image: hackathon-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackathon-backend
    ports:
      - 8080:8080
  
  frontend:
    image: hackathon-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackathon-frontend
    ports:
      - 3000:3000